name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

jobs:
  rust-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2

      - name: Linter
        run: |-
          rustup component add rustfmt
          cargo fmt -- --check

      - name: Clippy
        run: |-
          rustup component add clippy
          cargo clippy --locked --all-targets -- -D warnings

      - name: Test
        run: cargo test --locked --verbose

  js-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.x
      - run: deno lint
      - run: deno fmt --check
