name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

jobs:
  js-test-and-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno lint
      - run: deno fmt --check
      - run: deno install
      - run: deno test

  rust-linter:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-06-25
      - uses: Swatinem/rust-cache@v2

      - run: mkdir dist

      - name: Linter
        run: |-
          rustup component add rustfmt
          cargo fmt -- --check

      - name: Clippy
        run: |-
          rustup component add clippy
          cargo clippy --locked --all-targets -- -D warnings

  rust-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-06-25
      - uses: Swatinem/rust-cache@v2
      - run: mkdir dist
      - run: cargo test --locked --verbose
